### ISSUE TITLE
Tailscale windows support

### ISSUE THREAD

**Issue by aubreyyan** [tailscale/github-action#93] opened 2023-10-25 18:23 UTC
I'm getting the following error when I add tailscale to my github actions:

```
Run echo "::error title=⛔ error hint::Support Linux Only"
  echo "::error title=⛔ error hint::Support Linux Only"
  exit 1
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
```

The github workflow looks like this:

```
name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ '3.8' ]

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: actions/checkout@v3
  ```

Is my use case not supported?

**Comment by DentonGentry** [comment] 2023-10-25 18:31
This GitHub Action currently only supports Linux runners. The error message is "⛔ error hint::Support Linux Only"

**Comment by bradfitz** [comment] 2023-10-25 18:36
Dup of #61?

**Comment by DentonGentry** [comment] 2023-10-25 22:37
Duplicate of https://github.com/tailscale/github-action/issues/61

**Closed by DentonGentry** 2023-10-25 22:37 UTC
